const text = [
    "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Massa sed elementum tempus egestas sed sed risus. Ullamcorper sit amet risus nullam eget felis eget nunc. Dui accumsan sit amet nulla facilisi morbi tempus iaculis urna. Enim ut sem viverra aliquet. Ut consequat semper viverra nam libero justo laoreet sit amet. Volutpat consequat mauris nunc congue nisi vitae suscipit tellus mauris. Eu augue ut lectus arcu bibendum at. Massa sapien faucibus et molestie ac feugiat sed lectus vestibulum. Quis risus sed vulputate odio ut enim. Lacus viverra vitae congue eu consequat. Lacinia quis vel eros donec ac odio tempor orci. Nulla at volutpat diam ut venenatis tellus. Pretium vulputate sapien nec sagittis. Nisl pretium fusce id velit.",

    "Lorem ipsum dolor sit amet consectetur adipiscing. Bibendum at varius vel pharetra vel turpis nunc. Urna porttitor rhoncus dolor purus non enim praesent elementum facilisis. Neque sodales ut etiam sit amet nisl. Facilisis magna etiam tempor orci eu lobortis elementum nibh. Vitae semper quis lectus nulla at. Neque laoreet suspendisse interdum consectetur libero id. Odio pellentesque diam volutpat commodo sed. Velit aliquet sagittis id consectetur purus ut. Id neque aliquam vestibulum morbi blandit cursus risus. Tellus in metus vulputate eu.",

    "Enim sed faucibus turpis in eu mi bibendum neque egestas. Pharetra et ultrices neque ornare aenean euismod elementum nisi. Dolor purus non enim praesent elementum facilisis leo vel fringilla. Vel elit scelerisque mauris pellentesque pulvinar. A diam sollicitudin tempor id. Donec ac odio tempor orci. Tempus iaculis urna id volutpat lacus laoreet non curabitur gravida. Et tortor at risus viverra. Dolor purus non enim praesent elementum facilisis. Pellentesque diam volutpat commodo sed egestas egestas. Lectus nulla at volutpat diam ut venenatis. Est placerat in egestas erat imperdiet sed euismod. Nisi vitae suscipit tellus mauris a diam maecenas. Felis bibendum ut tristique et.",

    "Vestibulum morbi blandit cursus risus at ultrices mi tempus imperdiet. Dictum non consectetur a erat. Commodo odio aenean sed adipiscing diam donec adipiscing. Fusce ut placerat orci nulla pellentesque dignissim enim. Nec dui nunc mattis enim ut tellus elementum sagittis. Leo in vitae turpis massa sed elementum tempus egestas. Ornare aenean euismod elementum nisi quis eleifend. Aliquam etiam erat velit scelerisque in dictum. Feugiat pretium nibh ipsum consequat nisl vel pretium. Consectetur adipiscing elit duis tristique sollicitudin nibh sit amet commodo. Egestas sed tempus urna et pharetra pharetra massa. Cum sociis natoque penatibus et magnis dis parturient montes nascetur. Enim tortor at auctor urna nunc. Risus ultricies tristique nulla aliquet enim tortor at auctor. Turpis egestas sed tempus urna et pharetra pharetra massa.",

    "Tempor orci dapibus ultrices in iaculis nunc sed. Orci dapibus ultrices in iaculis nunc sed. Eros in cursus turpis massa tincidunt dui. Posuere ac ut consequat semper viverra nam. Vel fringilla est ullamcorper eget nulla facilisi etiam. Enim ut tellus elementum sagittis vitae et leo duis. Sed arcu non odio euismod. Sit amet nisl purus in mollis nunc. Faucibus vitae aliquet nec ullamcorper sit amet risus. Mattis rhoncus urna neque viverra justo. Luctus accumsan tortor posuere ac ut consequat semper viverra nam. Auctor eu augue ut lectus arcu bibendum at varius. Cursus mattis molestie a iaculis at erat. Risus ultricies tristique nulla aliquet. Ut lectus arcu bibendum at varius. Id venenatis a condimentum vitae sapien pellentesque. Sagittis eu volutpat odio facilisis mauris sit amet massa vitae. Neque gravida in fermentum et sollicitudin ac orci. Metus vulputate eu scelerisque felis imperdiet proin.",

    "Mattis molestie a iaculis at erat pellentesque. Eget gravida cum sociis natoque penatibus et. Sit amet aliquam id diam maecenas. Augue ut lectus arcu bibendum at varius vel. In vitae turpis massa sed elementum. Amet mauris commodo quis imperdiet. Erat velit scelerisque in dictum. Et tortor consequat id porta. Maecenas pharetra convallis posuere morbi leo urna molestie. Pulvinar elementum integer enim neque volutpat ac tincidunt vitae semper.",

    "Ut tristique et egestas quis ipsum suspendisse ultrices. Egestas congue quisque egestas diam in arcu cursus euismod quis. A arcu cursus vitae congue mauris rhoncus aenean vel elit. Nisl nisi scelerisque eu ultrices vitae auctor eu augue ut. Felis eget nunc lobortis mattis aliquam faucibus purus in. Arcu non odio euismod lacinia. Porta non pulvinar neque laoreet suspendisse interdum consectetur libero. In aliquam sem fringilla ut morbi tincidunt augue. Eleifend mi in nulla posuere sollicitudin aliquam. Vel eros donec ac odio tempor.",

    "Parturient montes nascetur ridiculus mus mauris vitae ultricies leo integer. Elit scelerisque mauris pellentesque pulvinar pellentesque habitant morbi. Sed pulvinar proin gravida hendrerit. Ac tortor dignissim convallis aenean et tortor at risus. A diam maecenas sed enim ut sem. Dictum sit amet justo donec enim diam vulputate. Nunc sed blandit libero volutpat sed cras ornare arcu dui. Pharetra diam sit amet nisl. Nunc id cursus metus aliquam eleifend mi in nulla. Pulvinar etiam non quam lacus. Purus non enim praesent elementum facilisis leo vel fringilla est. Ut tellus elementum sagittis vitae et leo. Consectetur adipiscing elit pellentesque habitant morbi tristique senectus et netus. Sed adipiscing diam donec adipiscing tristique risus. Nibh tellus molestie nunc non. Non curabitur gravida arcu ac tortor dignissim convallis. Consectetur lorem donec massa sapien faucibus et.",

    "Dictum non consectetur a erat nam at lectus. Viverra nam libero justo laoreet sit amet. Nulla facilisi nullam vehicula ipsum a arcu cursus vitae congue. Vitae aliquet nec ullamcorper sit amet. Porttitor massa id neque aliquam vestibulum morbi blandit. Non sodales neque sodales ut etiam. Vitae nunc sed velit dignissim sodales. Consectetur libero id faucibus nisl. Sed enim ut sem viverra aliquet eget sit amet. Lectus proin nibh nisl condimentum id. Non tellus orci ac auctor augue mauris. Vehicula ipsum a arcu cursus vitae congue. Integer enim neque volutpat ac tincidunt vitae semper. Mauris a diam maecenas sed enim ut. Nec tincidunt praesent semper feugiat nibh.",

    "Molestie ac feugiat sed lectus. Vitae turpis massa sed elementum. Non sodales neque sodales ut etiam sit amet nisl. Ornare suspendisse sed nisi lacus. Tellus in hac habitasse platea. Sit amet consectetur adipiscing elit pellentesque habitant. Cursus in hac habitasse platea dictumst quisque. Porttitor rhoncus dolor purus non. Tempor nec feugiat nisl pretium fusce id velit. Vitae ultricies leo integer malesuada nunc. Viverra suspendisse potenti nullam ac. Ut eu sem integer vitae. Ipsum dolor sit amet consectetur adipiscing elit. Blandit massa enim nec dui nunc. Dolor morbi non arcu risus quis varius quam quisque id. Viverra aliquet eget sit amet tellus. Dictum fusce ut placerat orci nulla pellentesque dignissim.",

    "Nibh praesent tristique magna sit amet purus gravida. Enim diam vulputate ut pharetra sit amet aliquam. Adipiscing diam donec adipiscing tristique. Nibh cras pulvinar mattis nunc sed blandit libero volutpat. Tortor posuere ac ut consequat semper viverra. Consectetur a erat nam at lectus urna duis. Vestibulum lorem sed risus ultricies tristique nulla aliquet. Quam viverra orci sagittis eu volutpat odio facilisis mauris. Vestibulum mattis ullamcorper velit sed ullamcorper morbi tincidunt ornare. Vestibulum mattis ullamcorper velit sed ullamcorper morbi tincidunt ornare. Nullam eget felis eget nunc lobortis mattis. Dui faucibus in ornare quam viverra orci sagittis. Blandit libero volutpat sed cras ornare arcu dui. Malesuada proin libero nunc consequat. Tempus egestas sed sed risus pretium quam vulputate dignissim suspendisse. Sit amet commodo nulla facilisi nullam vehicula ipsum a. Mauris rhoncus aenean vel elit. Eu mi bibendum neque egestas.",

    "Nec nam aliquam sem et tortor consequat. Nulla facilisi nullam vehicula ipsum a arcu cursus vitae congue. Amet aliquam id diam maecenas ultricies mi eget mauris. Ut tortor pretium viverra suspendisse potenti nullam ac tortor. Nisi est sit amet facilisis magna etiam tempor orci. Enim diam vulputate ut pharetra. Morbi enim nunc faucibus a pellentesque sit. Netus et malesuada fames ac turpis egestas maecenas pharetra. Massa massa ultricies mi quis hendrerit dolor magna eget. Tellus integer feugiat scelerisque varius morbi. Dis parturient montes nascetur ridiculus mus mauris. Eleifend quam adipiscing vitae proin sagittis nisl rhoncus mattis. Leo vel orci porta non pulvinar neque laoreet suspendisse. Ultrices in iaculis nunc sed augue lacus. Velit euismod in pellentesque massa placerat duis ultricies lacus sed. Vitae auctor eu augue ut lectus arcu bibendum at. Turpis egestas maecenas pharetra convallis. Turpis egestas pretium aenean pharetra magna.",

    "Lectus vestibulum mattis ullamcorper velit sed. Curabitur gravida arcu ac tortor. Vel fringilla est ullamcorper eget. Nunc scelerisque viverra mauris in aliquam sem. Massa eget egestas purus viverra accumsan. Orci ac auctor augue mauris augue neque gravida in fermentum. Egestas integer eget aliquet nibh praesent tristique. Dignissim enim sit amet venenatis urna cursus eget nunc. Cras tincidunt lobortis feugiat vivamus at augue eget arcu dictum. Sit amet est placerat in egestas. Scelerisque in dictum non consectetur a erat. Fermentum et sollicitudin ac orci. Ultrices gravida dictum fusce ut placerat. Vitae aliquet nec ullamcorper sit. Purus in massa tempor nec feugiat nisl pretium fusce. Etiam tempor orci eu lobortis elementum nibh tellus. Cras semper auctor neque vitae tempus quam pellentesque nec. Lobortis elementum nibh tellus molestie. Magna ac placerat vestibulum lectus mauris ultrices eros.",

    "Amet nisl suscipit adipiscing bibendum. Sit amet tellus cras adipiscing. Ornare aenean euismod elementum nisi quis eleifend quam adipiscing. Enim neque volutpat ac tincidunt vitae semper quis. Magna eget est lorem ipsum dolor sit. Ut sem nulla pharetra diam. Et ligula ullamcorper malesuada proin libero nunc consequat. Arcu non odio euismod lacinia at quis risus sed vulputate. Vitae et leo duis ut diam quam nulla porttitor. Diam quam nulla porttitor massa id neque aliquam vestibulum. Magnis dis parturient montes nascetur ridiculus mus mauris. Turpis massa sed elementum tempus egestas sed sed. Morbi enim nunc faucibus a pellentesque sit amet.",

    "Diam phasellus vestibulum lorem sed risus. Pretium vulputate sapien nec sagittis aliquam malesuada bibendum arcu vitae. Gravida quis blandit turpis cursus in hac habitasse platea dictumst. Sed augue lacus viverra vitae congue eu. Dictum at tempor commodo ullamcorper a lacus vestibulum. Vestibulum mattis ullamcorper velit sed ullamcorper morbi tincidunt ornare massa. Consequat nisl vel pretium lectus quam id. Quis varius quam quisque id. Urna cursus eget nunc scelerisque viverra. Hendrerit gravida rutrum quisque non. Viverra nam libero justo laoreet sit amet. Parturient montes nascetur ridiculus mus mauris. Dui id ornare arcu odio ut sem nulla. Eget arcu dictum varius duis. Scelerisque varius morbi enim nunc faucibus a. Massa enim nec dui nunc mattis enim ut tellus elementum. Convallis tellus id interdum velit laoreet id donec ultrices. Elit duis tristique sollicitudin nibh. Vitae semper quis lectus nulla at volutpat diam.",

    "Tempor orci dapibus ultrices in iaculis. Quis commodo odio aenean sed. Scelerisque fermentum dui faucibus in ornare quam viverra orci. Arcu non sodales neque sodales. Id semper risus in hendrerit gravida rutrum quisque non. Viverra accumsan in nisl nisi scelerisque eu ultrices vitae. Laoreet id donec ultrices tincidunt arcu non sodales neque sodales. Lectus urna duis convallis convallis tellus id. Dui faucibus in ornare quam viverra orci sagittis eu volutpat. Nec sagittis aliquam malesuada bibendum arcu vitae elementum curabitur.",

    "Massa tincidunt nunc pulvinar sapien et ligula. Dolor magna eget est lorem ipsum dolor. Morbi tristique senectus et netus et malesuada. Amet consectetur adipiscing elit pellentesque. Nisi quis eleifend quam adipiscing vitae proin. Neque egestas congue quisque egestas diam in arcu cursus. Viverra suspendisse potenti nullam ac tortor vitae purus faucibus ornare. Pellentesque diam volutpat commodo sed. Cras pulvinar mattis nunc sed blandit libero volutpat sed. Sit amet consectetur adipiscing elit ut aliquam purus sit amet. Faucibus ornare suspendisse sed nisi lacus sed viverra tellus. Tristique magna sit amet purus gravida quis blandit turpis cursus.",

    "Pharetra sit amet aliquam id diam maecenas ultricies. Faucibus ornare suspendisse sed nisi lacus sed viverra tellus in. Tortor aliquam nulla facilisi cras fermentum odio eu. Nibh praesent tristique magna sit. Nibh sit amet commodo nulla facilisi. Sed sed risus pretium quam vulputate. Purus sit amet volutpat consequat mauris nunc congue. Pellentesque habitant morbi tristique senectus et netus et malesuada. Amet tellus cras adipiscing enim eu turpis egestas pretium aenean. Dui faucibus in ornare quam. Mauris rhoncus aenean vel elit scelerisque mauris pellentesque pulvinar pellentesque.",

    "Eu sem integer vitae justo eget magna fermentum iaculis. Nisi quis eleifend quam adipiscing. Nibh ipsum consequat nisl vel pretium lectus quam id. At lectus urna duis convallis convallis tellus id interdum velit. Placerat vestibulum lectus mauris ultrices eros in cursus turpis massa. A iaculis at erat pellentesque adipiscing commodo elit. Nec feugiat nisl pretium fusce id velit ut tortor pretium. Amet porttitor eget dolor morbi non arcu risus quis varius. Habitant morbi tristique senectus et. Nunc sed velit dignissim sodales ut. Orci eu lobortis elementum nibh tellus molestie nunc non blandit. Amet tellus cras adipiscing enim eu turpis egestas. Arcu cursus euismod quis viverra. Vel orci porta non pulvinar neque. Diam quam nulla porttitor massa id neque aliquam vestibulum morbi. Eu turpis egestas pretium aenean.",

    "Mattis rhoncus urna neque viverra justo nec ultrices dui sapien. Vitae nunc sed velit dignissim sodales ut eu sem. Sapien nec sagittis aliquam malesuada bibendum arcu vitae. Fusce ut placerat orci nulla pellentesque dignissim enim sit. Leo in vitae turpis massa sed elementum tempus egestas sed. Quisque id diam vel quam elementum pulvinar etiam non quam. Tellus pellentesque eu tincidunt tortor aliquam nulla facilisi cras. Morbi non arcu risus quis varius quam. Facilisis magna etiam tempor orci eu lobortis elementum nibh. Dis parturient montes nascetur ridiculus mus mauris. Accumsan sit amet nulla facilisi morbi tempus. Nisl condimentum id venenatis a. Augue ut lectus arcu bibendum. Dictum sit amet justo donec enim diam vulputate ut pharetra. Odio ut sem nulla pharetra diam sit amet. Sed viverra ipsum nunc aliquet bibendum enim. Urna id volutpat lacus laoreet non curabitur. Ipsum consequat nisl vel pretium lectus quam id leo. Non quam lacus suspendisse faucibus interdum. Ut aliquam purus sit amet."
];
const form = document.querySelector(".lorem-form");
const amount = document.getElementById("amount");
const result = document.querySelector(".lorem-text");

form.addEventListener("submit", function (event) {
    event.preventDefault();
    let randomText = Math.floor(Math.random() * text.length);
    const amountValue = parseInt(amount.value);
    result.innerHTML = "";
    // No number entered
    // Negative number
    // Greater than 20
    if (isNaN(amountValue) || amountValue > 20 || amountValue <= 0) {
        result.innerHTML = `<p> ${text[randomText]}</p>`;
    } else {
        let tempText = text.slice(0, amountValue);
        tempText.map(function (item) {
            result.innerHTML += `<p>${item}</p>`;
        });
    }
});